port: 8080
name: amberframework.org
logging:
  severity: info
  colorize: false
  filter:
    - password
    - confirm_password
  skip:
    -
  context:
    - 

host: 0.0.0.0
port_reuse: true
process_count: 1
